before_install:
  - gem install bundler
language: ruby
rvm:
  - 1.18.3
before_script:
  - "rake"
  - bash build/post_build.sh
env:
  global:
    secure: lJ+y3RybTKzqHuoOrRMiOOdNY6+3IJHoE0lFK4omtq2uSvx8pV/kjyRYAzdPIvfekxJ1LjBYKN2FMVA1bvv7v9/7427LuiUECmQkBSQNhyB7WCJh9NiHGSVNZgOFrzaE36NElmXHt5rg8hC5kIWS404hMhhzU60mDHZhr16dgQk=

branches:
  except:
    - gh-pages

script:
  - bash build/gh-pages-report.sh